// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateRegistrationData, CreateRegistrationResponses, GetAuctionData, GetAuctionErrors, GetAuctionResponses, GetHealthData, GetHealthResponses, ListAuctionsData, ListAuctionsResponses, PlaceBidData, PlaceBidResponses, ReceivePaystackWebhookData, ReceivePaystackWebhookResponses, RedeemEntryCodeData, RedeemEntryCodeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Check API process health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List available auctions
 */
export const listAuctions = <ThrowOnError extends boolean = false>(options?: Options<ListAuctionsData, ThrowOnError>): RequestResult<ListAuctionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAuctionsResponses, unknown, ThrowOnError>({ url: '/api/v1/auctions', ...options });

/**
 * Get an auction by ID
 */
export const getAuction = <ThrowOnError extends boolean = false>(options: Options<GetAuctionData, ThrowOnError>): RequestResult<GetAuctionResponses, GetAuctionErrors, ThrowOnError> => (options.client ?? client).get<GetAuctionResponses, GetAuctionErrors, ThrowOnError>({ url: '/api/v1/auctions/{id}', ...options });

/**
 * Create or resume an auction registration
 */
export const createRegistration = <ThrowOnError extends boolean = false>(options: Options<CreateRegistrationData, ThrowOnError>): RequestResult<CreateRegistrationResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateRegistrationResponses, unknown, ThrowOnError>({
    url: '/api/v1/registrations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Redeem a paid registration entry code
 */
export const redeemEntryCode = <ThrowOnError extends boolean = false>(options: Options<RedeemEntryCodeData, ThrowOnError>): RequestResult<RedeemEntryCodeResponses, unknown, ThrowOnError> => (options.client ?? client).post<RedeemEntryCodeResponses, unknown, ThrowOnError>({
    url: '/api/v1/registrations/redeem',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Receive a verified Paystack charge event
 */
export const receivePaystackWebhook = <ThrowOnError extends boolean = false>(options: Options<ReceivePaystackWebhookData, ThrowOnError>): RequestResult<ReceivePaystackWebhookResponses, unknown, ThrowOnError> => (options.client ?? client).post<ReceivePaystackWebhookResponses, unknown, ThrowOnError>({
    url: '/api/v1/payments/webhooks/paystack',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Place an idempotent live auction bid
 */
export const placeBid = <ThrowOnError extends boolean = false>(options: Options<PlaceBidData, ThrowOnError>): RequestResult<PlaceBidResponses, unknown, ThrowOnError> => (options.client ?? client).post<PlaceBidResponses, unknown, ThrowOnError>({
    url: '/api/v1/bids',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
