// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type AuctionResponseDto = {
    id: string;
    title: string;
    currency: string;
    /**
     * Integer amount in the currency minor unit
     */
    startingPriceMinor: string;
    /**
     * Integer amount in the currency minor unit
     */
    reservePriceMinor?: {
        [key: string]: unknown;
    };
    depositAmountMinor: string;
    minIncrementMinor: string;
    status: 'SCHEDULED' | 'ACTIVE' | 'CLOSED';
    startsAt: string;
    endsAt: string;
    effectiveEndsAt: string;
    createdAt: string;
    updatedAt: string;
};

export type CreateRegistrationDto = {
    auctionId: string;
    /**
     * Email passed to Paystack for this deposit
     */
    email: string;
};

export type RegistrationResponseDto = {
    registrationId: string;
    checkoutUrl: string;
    status: 'PENDING' | 'HELD' | 'APPLIED' | 'REFUNDED' | 'FORFEIT';
    /**
     * Paystack reports this deposit as paid but the webhook has not confirmed it yet; checkoutUrl is empty and the payer must not pay again
     */
    awaitingConfirmation: boolean;
};

export type RedeemEntryCodeDto = {
    auctionId: string;
    code: string;
};

export type RedemptionResponseDto = {
    auctionId: string;
    registrationId: string;
    admitted: boolean;
    expiresAt: string;
    /**
     * Short-lived signed token for the v1 auction WebSocket
     */
    roomToken: string;
};

export type PaystackChargeDataDto = {
    id: number;
    reference: string;
    status: 'success';
    amount: number;
    currency: string;
};

export type PaystackWebhookDto = {
    event: 'charge.success';
    data: PaystackChargeDataDto;
};

export type PaymentWebhookResponseDto = {
    received: boolean;
    duplicate?: boolean;
};

export type PlaceBidDto = {
    auctionId: string;
    /**
     * Client-generated idempotency key
     */
    requestId: string;
    /**
     * Integer amount in the currency minor unit
     */
    amountMinor: number;
};

export type BidResponseDto = {
    status: 'ACCEPTED' | 'DUPLICATE' | 'CLOSED' | 'UNDERBID';
    amountMinor?: number;
    sequence?: number;
    effectiveEndsAt?: string;
    detail?: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    200: unknown;
};

export type ListAuctionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auctions';
};

export type ListAuctionsResponses = {
    200: Array<AuctionResponseDto>;
};

export type ListAuctionsResponse = ListAuctionsResponses[keyof ListAuctionsResponses];

export type GetAuctionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/auctions/{id}';
};

export type GetAuctionErrors = {
    /**
     * Auction not found
     */
    404: unknown;
};

export type GetAuctionResponses = {
    200: AuctionResponseDto;
};

export type GetAuctionResponse = GetAuctionResponses[keyof GetAuctionResponses];

export type CreateRegistrationData = {
    body: CreateRegistrationDto;
    headers: {
        'x-telegram-init-data': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/registrations';
};

export type CreateRegistrationResponses = {
    201: RegistrationResponseDto;
};

export type CreateRegistrationResponse = CreateRegistrationResponses[keyof CreateRegistrationResponses];

export type RedeemEntryCodeData = {
    body: RedeemEntryCodeDto;
    headers: {
        'x-telegram-init-data': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/registrations/redeem';
};

export type RedeemEntryCodeResponses = {
    201: RedemptionResponseDto;
};

export type RedeemEntryCodeResponse = RedeemEntryCodeResponses[keyof RedeemEntryCodeResponses];

export type ReceivePaystackWebhookData = {
    body: PaystackWebhookDto;
    headers: {
        'x-paystack-signature': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/payments/webhooks/paystack';
};

export type ReceivePaystackWebhookResponses = {
    200: PaymentWebhookResponseDto;
};

export type ReceivePaystackWebhookResponse = ReceivePaystackWebhookResponses[keyof ReceivePaystackWebhookResponses];

export type PlaceBidData = {
    body: PlaceBidDto;
    headers: {
        'x-telegram-init-data': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/bids';
};

export type PlaceBidResponses = {
    201: BidResponseDto;
};

export type PlaceBidResponse = PlaceBidResponses[keyof PlaceBidResponses];
